### ISSUE TITLE
Error after compile on production mode 

### ISSUE THREAD

**Issue by osmansorkar** [cloudflare/Cloudflare-Magento#38]
Fatal error: Uncaught TypeError: Argument 1 passed to CF\Integration\DefaultIntegration::__construct() must be an instance of CF\Integration\ConfigInterface, instance of Magento\Framework\ObjectManager\ObjectManager given, called in /var/www/clients/client0/web1/web/lib/internal/Magento/Framework/ObjectManager/Factory/AbstractFactory.php on line 93 and defined in /var/www/clients/client0/web1/web/vendor/cloudflare/cloudflare-plugin-backend/src/Integration/DefaultIntegration.php:20 Stack trace: #0 /var/www/clients/client0/web1/web/lib/internal/Magento/Framework/ObjectManager/Factory/AbstractFactory.php(93): CF\Integration\DefaultIntegration->__construct(Object(Magento\Framework\ObjectManager\ObjectManager)) #1 /var/www/clients/client0/web1/web/lib/internal/Magento/Framework/ObjectManager/Factory/Compiled.php(88): Magento\Framework\ObjectManager\Factory\AbstractFactory->createObject('CF\\Integration\\...', Array) #2 /var/www/clients/client0/web1/web/lib/internal/Magento/Framework/ObjectManager/Factory/Compiled.php(130): Mag in /var/www/clients/client0/web1/web/vendor/cloudflare/cloudflare-plugin-backend/src/Integration/DefaultIntegration.php on line 20

**Comment by scuf-davidg** [comment]
Same issue for me.

**Comment by kartguru** [comment]
ditto ... but in development mode

Recoverable Error: Argument 1 passed to CF\Integration\DefaultIntegration::__construct() must be an instance of CF\Integration\ConfigInterface, instance of Magento\Framework\ObjectManager\ObjectManager given, called in /public_html/vendor/magento/framework/ObjectManager/Factory/AbstractFactory.php on line 93 and defined in /public_html/vendor/cloudflare/cloudflare-plugin-backend/src/Integration/DefaultIntegration.php on line 20

**Comment by ooples** [comment]
Is there anyone working on this issue?

**Comment by jwineman** [comment]
I'm still looking into this.

**Comment by jwineman** [comment]
Fixed in https://github.com/cloudflare/Cloudflare-Magento/pull/47

Can you upgrade to 1.1.1 and let me know if this is resolved please?
