### ISSUE TITLE
PHP Fatal error:  Interface 'CF\Integration\IntegrationAPIInterface' not found in CloudFlare/Plugin/Backend/MagentoAPI.php

### ISSUE THREAD

**Issue by navinbhudiya** [cloudflare/Cloudflare-Magento#65]
Hello,
I added the cloudflare magento 2 plugin to my magento store.
But while i am installing module using  php magento setup:upgrade command at that time i am facing issue 
https://prnt.sc/gyg7rz

Magento version 2.1.6

Thanks in Advance!
Navin Bhudiya

**Comment by thellimist** [comment]
have you ran the following scripts?

```
composer require cloudflare/cloudflare-magento
composer update
```

For whole installation steps you can read [README.md](https://github.com/cloudflare/Cloudflare-Magento)

**Comment by navinbhudiya** [comment]
Thank you for replay , its working fine after running 
composer require cloudflare/cloudflare-magento
composer update
